name: merge_stage_test

on:
  push:
    paths-ignore:
      - ".github/**.md"
      - "docker/**"
      - "docs/**"
      - "README.md"
      - "CONTRIBUTING.md"
      - ".pre-commit-config.yaml"
      - 'configs/**'
      - 'demo/**'
      - 'projects/**'
      - 'resources/**'
      - 'tools/**'
      - '.dev_scripts/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_gpu:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - python-version: '3.12'  # maximum version
            torch: '2.10.0'
            container: 'nvidia/cuda:12.9.1-cudnn-runtime-ubuntu22.04'
    container:
      image: ${{ matrix.container }}
    env:
        UV_CACHE_DIR: /__w/_uv_cache # set cache to be on same disk to avoid hardlink copies.
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC
        PIP_PRE: 1 # TODO: until real release
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          python-version: ${{ matrix.python-version }}
          cache-local-path: /__w/_uv_cache
      - name: Fetch GPG keys
        run: |
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y tzdata ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libxrender-dev libc6 libc6-dev
          apt-get clean -y
      - name: Install torch
        run: |
          uv pip install -v --torch-backend=auto torch==${{ matrix.torch }} torchvision
          uv cache clean
      - name: Install mmdet3d dependencies
        run: |
          uv pip install onedl-mim
          mim install onedl-mmcv --only-binary=onedl-mmcv
          uv pip install -r pyproject.toml --all-extras
      - name: Build and install
        run: uv pip install -e .
      - name: Install test dependencies
        run: uv pip install -r pyproject.toml --group tests
      - name: Run unit tests with coverage
        run: |
          set -e
          uv run coverage run --branch --source mmdet3d -m pytest tests/
          uv run coverage xml
